name: Create PR master -> main

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Create or Update PR
        run: |
          # Check for existing PR
          PR_EXISTS=$(gh pr list --head master --base main --state open --json number -q '.[0].number')

          if [ -z "$PR_EXISTS" ]; then
            echo "Creating a new PR from master to main..."
            gh pr create --title "Auto Merge: master → main" \
                         --body "This PR was automatically created to merge changes from master into main." \
                         --base main --head master
          else
            echo "PR already exists: #$PR_EXISTS"
          fi
